### ISSUE TITLE
Kisi uv

### ISSUE THREAD

**Issue by Angkitbharata** [Angkitbharata/jendfocc#12]
Python 3.9.7 (default, Oct  6 2021, 01:34:26)
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> ^K..
  File "<stdin>", line 1

    ..
    ^
SyntaxError: invalid syntax
>>> bsi ,..%59mhjmuv9h
  File "<stdin>", line 1
    bsi ,..%59mhjmuv9h
         ^
SyntaxError: invalid syntax
>>> xvygpr cyubohyuiyt8hvibk ,5 79,,,>.lhbyify
  File "<stdin>", line 1
    xvygpr cyubohyuiyt8hvibk ,5 79,,,>.lhbyify
           ^
SyntaxError: invalid syntax
>>> nygu8xupvb 7ksurucibsrZyci
  File "<stdin>", line 1
    nygu8xupvb 7ksurucibsrZyci
               ^
SyntaxError: invalid syntax
>>> 0pLfuoyffichldG<OSYRYA&^E%C
  File "<stdin>", line 1
    0pLfuoyffichldG<OSYRYA&^E%C
     ^
SyntaxError: invalid syntax
>>> A757jzixufbjztjovh i0&248 8
  File "<stdin>", line 1
    A757jzixufbjztjovh i0&248 8
                       ^
SyntaxError: invalid syntax
>>> ayhruy5azGX&SITDUTDYCFURYUA<XGHJFGIIDFI
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'ayhruy5azGX' is not defined
>>> KHHOGS&TUSGYRYZY^ruf8ilgkdekcg 5a iugeg
  File "<stdin>", line 1
    KHHOGS&TUSGYRYZY^ruf8ilgkdekcg 5a iugeg
                                   ^
SyntaxError: invalid syntax
>>> jro,c9zdy8ufhx6gxv8ftZF0dy58du9c
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'jro' is not defined
>>> otOt63srtizGu6ry8birgcy79ryodkBhxfudt9y8yucuxg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'otOt63srtizGu6ry8birgcy79ryodkBhxfudt9y8yucuxg' is not defined
>>> a7y66e7ehhyyfChufohiCilfziur7lftsfyfdtzh  cogirfigs8t  ocojvl uh bohfvj b8hfzb ovd8y 4957r0hjju yr7hnhuc6u vxklch   giicucug3tguvuhkgyojt5yitgrhhdid@7567w7xR8w5cifIi8x
  File "<stdin>", line 1
    a7y66e7ehhyyfChufohiCilfziur7lftsfyfdtzh  cogirfigs8t  ocojvl uh bohfvj b8hfzb ovd8y 4957r0hjju yr7hnhuc6u vxklch   giicucug3tguvuhkgyojt5yitgrhhdid@7567w7xR8w5cifIi8x
                                              ^
SyntaxError: invalid syntax
>>> luy563dHggyu7378 jkz#356%  i7pgohcgt  spx fojhutx
  File "<stdin>", line 1
    luy563dHggyu7378 jkz#356%  i7pgohcgt  spx fojhutx
                     ^
SyntaxError: invalid syntax
>>> ktum

**Comment by Angkitbharata** [comment]
> Python 3.9.7 (default, Oct  6 2021, 01:34:26)
> [GCC 11.1.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> ^K..
>   File "<stdin>", line 1
> 
>     ..
>     ^
> SyntaxError: invalid syntax
> >>> bsi ,..%59mhjmuv9h
>   File "<stdin>", line 1
>     bsi ,..%59mhjmuv9h
>          ^
> SyntaxError: invalid syntax
> >>> xvygpr cyubohyuiyt8hvibk ,5 79,,,>.lhbyify
>   File "<stdin>", line 1
>     xvygpr cyubohyuiyt8hvibk ,5 79,,,>.lhbyify
>            ^
> SyntaxError: invalid syntax
> >>> nygu8xupvb 7ksurucibsrZyci
>   File "<stdin>", line 1
>     nygu8xupvb 7ksurucibsrZyci
>                ^
> SyntaxError: invalid syntax
> >>> 0pLfuoyffichldG<OSYRYA&^E%C
>   File "<stdin>", line 1
>     0pLfuoyffichldG<OSYRYA&^E%C
>      ^
> SyntaxError: invalid syntax
> >>> A757jzixufbjztjovh i0&248 8
>   File "<stdin>", line 1
>     A757jzixufbjztjovh i0&248 8
>                        ^
> SyntaxError: invalid syntax
> >>> ayhruy5azGX&SITDUTDYCFURYUA<XGHJFGIIDFI
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'ayhruy5azGX' is not defined
> >>> KHHOGS&TUSGYRYZY^ruf8ilgkdekcg 5a iugeg
>   File "<stdin>", line 1
>     KHHOGS&TUSGYRYZY^ruf8ilgkdekcg 5a iugeg
>                                    ^
> SyntaxError: invalid syntax
> >>> jro,c9zdy8ufhx6gxv8ftZF0dy58du9c
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'jro' is not defined
> >>> otOt63srtizGu6ry8birgcy79ryodkBhxfudt9y8yucuxg
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'otOt63srtizGu6ry8birgcy79ryodkBhxfudt9y8yucuxg' is not defined
> >>> a7y66e7ehhyyfChufohiCilfziur7lftsfyfdtzh  cogirfigs8t  ocojvl uh bohfvj b8hfzb ovd8y 4957r0hjju yr7hnhuc6u vxklch   giicucug3tguvuhkgyojt5yitgrhhdid@7567w7xR8w5cifIi8x
>   File "<stdin>", line 1
>     a7y66e7ehhyyfChufohiCilfziur7lftsfyfdtzh  cogirfigs8t  ocojvl uh bohfvj b8hfzb ovd8y 4957r0hjju yr7hnhuc6u vxklch   giicucug3tguvuhkgyojt5yitgrhhdid@7567w7xR8w5cifIi8x
>                                               ^
> SyntaxError: invalid syntax
> >>> luy563dHggyu7378 jkz#356%  i7pgohcgt  spx fojhutx
>   File "<stdin>", line 1
>     luy563dHggyu7378 jkz#356%  i7pgohcgt  spx fojhutx
>                      ^
> SyntaxError: invalid syntax
> >>> ktum
